export const CONFIG = Object.freeze({
  schedulerTickMs: 1_000,
  failedTaskRetryMs: 15_000,
  maxTasksPerTick: 3,
  lightweightMaxTasksPerTick: 1,
  mediumMaxTasksPerTick: 2,
  noticeCooldownMs: 5 * 60_000,
  lightweightModeHomeRam: 32,
  fullModeHomeRam: 128,
  dashboardMinimumHomeRam: 32,
  overviewStatsEnabled: true,
  autoUpdateEnabled: true,
  autoUpdateIntervalMs: 15 * 60_000,
  autoUpdateRepository: "ame824/autoDoIt",
  autoUpdateBranch: "main",

  hackMoneyFraction: 0.10,
  growMoneyThreshold: 0.75,
  securityTolerance: 5,

  purchasedServerPrefix: "autodoit",
  purchasedServerStartRam: 2,
  purchasedServerBudgetFraction: 0.15,
  ramFocusPurchasedServerBudgetFraction: 0.01,
  ramFocusInfrastructureBudgetBankFraction: 0.15,
  homeUpgradeBudgetFraction: 0.25,
  homeRamFocusReserveFraction: 0.10,
  homeRamFocusMinimumReserve: 32,
  homeRamMediumRatio: 0.50,

  hacknetBudgetFraction: 0.05,
  ramFocusHacknetBudgetFraction: 0.01,
  stockBudgetFraction: 0.10,
  gangEquipmentBudgetFraction: 0.01,
  sleeveAugBudgetFraction: 0.01,

  minimumAugsBeforeInstall: 5,
  augmentationMoneyReserve: 1_000_000,

  casinoEnabled: true,
  casinoMinimumMoney: 1_000_000,
  casinoMaximumBet: 100_000_000,
  casinoTargetEarnings: 10_000_000_000,

  ipvGoEnabled: true,
  ipvGoBoardSize: 9,
  ipvGoOpponents: ["Netburners", "Slum Snakes", "The Black Hand", "Tetrads", "Daedalus", "Illuminati"],

  exploitsEnabled: true,

  darknetEnabled: true,
  darknetPort: 19,
  darknetWorkerDepth: 40,
  darknetWorkerMaxThreads: 64,
  darknetWorkerScanMs: 5_000,
  darknetWorkerEventCooldownMs: 60_000,
  darknetLabyrinthMaximumSteps: 10_000,
  darknetBootstrapMaxThreads: 512,
  darknetAutoStormSeed: true,
  darknetStormMinimumDepth: 15,
  darknetStormStuckMs: 2 * 60_000,

  preferredCityFactions: ["Sector-12", "Aevum"],
  companyTargets: [
    "ECorp",
    "MegaCorp",
    "KuaiGong International",
    "Four Sigma",
    "NWO",
    "Blade Industries",
    "OmniTek Incorporated",
    "Bachman & Associates",
    "Clarke Incorporated",
    "Fulcrum Technologies",
  ],
  jobFields: ["Software", "IT", "Security", "Business"],

  bitNodeOrder: [4, 5, 10, 2, 3, 7, 9, 8, 6, 11, 12, 13, 14, 15, 1],
});

export const WORKER_FILES = Object.freeze([
  "/workers/hack.js",
  "/workers/grow.js",
  "/workers/weaken.js",
  "/workers/share.js",
]);

export const TASKS = Object.freeze([
  {
    file: "/tasks/check-home-ram.js",
    intervalMs: 30_000,
    priority: 112,
    lightweight: true,
    bootstrap: true,
    lightweightPriority: 135,
    mediumPriority: 135,
  },
  {
    file: "/tasks/check-job.js",
    intervalMs: 60_000,
    priority: 111,
    lightweight: true,
    bootstrap: true,
    lightweightPriority: 118,
    mediumPriority: 118,
  },
  {
    file: "/special/manage-casino.js",
    intervalMs: 45_000,
    priority: 110,
    exclusive: true,
    lightweight: true,
    lightweightPriority: 130,
    mediumPriority: 115,
    fullPriority: 170,
  },
  {
    file: "/tools/auto-updater.js",
    intervalMs: 60_000,
    priority: 108,
    lightweight: true,
    lightweightPriority: 115,
    mediumPriority: 100,
    fullPriority: 165,
  },
  { file: "/special/manage-exploits.js", intervalMs: 60_000, priority: 105, exclusive: true, fullPriority: 175 },
  {
    file: "/tasks/root-network.js",
    intervalMs: 5_000,
    priority: 100,
    lightweight: true,
    bootstrap: true,
    lightweightPriority: 129,
    mediumPriority: 127,
    fullPriority: 205,
  },
  {
    file: "/tasks/deploy-workers.js",
    intervalMs: 10_000,
    priority: 95,
    lightweight: true,
    bootstrap: true,
    lightweightPriority: 127,
    mediumPriority: 126,
    fullPriority: 200,
  },
  {
    file: "/special/manage-contracts.js",
    intervalMs: 60_000,
    priority: 80,
    lightweight: true,
    lightweightPriority: 100,
    mediumPriority: 122,
    fullPriority: 160,
  },
  {
    file: "/tasks/manage-hacking-lite.js",
    intervalMs: 5_000,
    priority: 89,
    lightweight: false,
    bootstrap: true,
    bootstrapOnly: true,
    lightweightPriority: 120,
  },
  {
    file: "/tasks/manage-hacking.js",
    intervalMs: 3_000,
    priority: 90,
    lightweight: true,
    lightweightPriority: 120,
    mediumPriority: 126,
    fullPriority: 195,
  },
  {
    file: "/tasks/manage-programs.js",
    intervalMs: 30_000,
    priority: 75,
    lightweight: true,
    lightweightPriority: 130,
    mediumPriority: 128,
    fullPriority: 210,
  },
  {
    file: "/tasks/manage-home-ram.js",
    intervalMs: 15_000,
    priority: 94,
    preflightAfterExclusive: true,
    lightweight: true,
    lightweightPriority: 125,
    mediumPriority: 130,
  },
  { file: "/tasks/manage-home.js", intervalMs: 60_000, priority: 74, fullPriority: 150 },
  { file: "/tasks/manage-backdoors.js", intervalMs: 30_000, priority: 70, medium: true, mediumPriority: 124, fullPriority: 190 },
  { file: "/tasks/manage-factions.js", intervalMs: 20_000, priority: 65, medium: true, mediumPriority: 123, fullPriority: 185 },
  {
    file: "/tasks/manage-jobs.js",
    intervalMs: 60_000,
    priority: 60,
    lightweight: true,
    lightweightPriority: 88,
    mediumPriority: 120,
  },
  { file: "/tasks/manage-augmentations.js", intervalMs: 20_000, priority: 55, medium: true, mediumPriority: 129, fullPriority: 184 },
  { file: "/tasks/manage-progression.js", intervalMs: 10_000, priority: 54, medium: true, mediumPriority: 130, fullPriority: 220 },
  {
    file: "/tasks/manage-purchased-servers.js",
    intervalMs: 15_000,
    priority: 50,
    preflightAfterExclusive: true,
    lightweight: true,
    lightweightPriority: 85,
    mediumPriority: 90,
  },
  {
    file: "/tasks/manage-hacknet.js",
    intervalMs: 10_000,
    priority: 45,
    lightweight: true,
    lightweightPriority: 80,
    mediumPriority: 89,
  },
  { file: "/special/manage-gang.js", intervalMs: 10_000, priority: 40, bitNodes: [2], mediumPriority: 121, fullPriority: 188 },
  { file: "/special/manage-darknet.js", intervalMs: 30_000, priority: 38, bitNodes: [15], mediumPriority: 121, fullPriority: 188 },
  { file: "/special/manage-sleeves.js", intervalMs: 20_000, priority: 35, bitNodes: [10], mediumPriority: 121, fullPriority: 188 },
  { file: "/special/manage-bladeburner.js", intervalMs: 10_000, priority: 30, bitNodes: [6, 7], mediumPriority: 121, fullPriority: 188 },
  { file: "/special/manage-corporation.js", intervalMs: 20_000, priority: 25, bitNodes: [3], mediumPriority: 121, fullPriority: 188 },
  { file: "/special/manage-stocks.js", intervalMs: 10_000, priority: 20, bitNodes: [8], mediumPriority: 121, fullPriority: 188 },
  { file: "/special/manage-ipvgo.js", intervalMs: 60_000, priority: 15, bitNodes: [14], mediumPriority: 121, fullPriority: 188 },
]);
