export const LANGUAGE_FILE = "/data/autoDoIt-language.txt";
export const LANGUAGE = Object.freeze({ de: "de", en: "en" });

const DASHBOARD_TEXT = Object.freeze({
  de: {
    language: "Sprache",
    online: "ONLINE",
    stopped: "GESTOPPT",
    player: "SPIELER",
    money: "Geld",
    hacking: "Hacking",
    sourceFiles: "SourceFiles",
    resources: "RESSOURCEN",
    homeRam: "Home-RAM",
    ramPurchase: "RAM-Kauf",
    ramAutomatic: "automatisch",
    ramManual: "nur manuell",
    ramWaiting: "automatisch · wartet auf Geld",
    ramUnavailable: "wartet auf freien Modul-RAM",
    ramComplete: "Ziel erreicht",
    ramChecking: "wird geprüft",
    network: "Netzwerk",
    rootedServers: "Server mit Root-Zugriff",
    automation: "AUTOMATISIERUNG",
    mode: "Modus",
    bootstrap: "BOOTSTRAP (minimal)",
    lightweight: "STARTPHASE (leicht)",
    medium: "MITTELSTUFE (RAM + Source-Files)",
    full: "VOLLBETRIEB",
    homeExpansion: "Home-RAM-Ziel",
    allModulesReleased: "Alle Module ab {ram} freigegeben",
    modules: "Module",
    active: "aktiv",
    executable: "ausführbar",
    phase: "Phase",
    processes: "Prozesse",
    threads: "Threads",
    dashboard: "Dashboard",
    autoUpdate: "Auto-Update",
    updateDisabled: "deaktiviert",
    updateChecking: "wird geprüft",
    updateCurrent: "aktuell",
    updateFound: "gefunden · Installation startet",
    updateFailed: "Prüfung fehlgeschlagen",
    updateUnknown: "noch nicht geprüft",
    nextUpdateCheck: "nächste Prüfung",
    efficiency: "EFFIZIENZ",
    moneyPerSecond: "Geld Ø/s",
    runTime: "Laufzeit",
    augmentations: "Augs",
    workers: "Worker",
    manualActions: "MANUELLE AKTIONEN",
    noNotices: "Keine aktuellen Hinweise",
    recentActivity: "LETZTE AKTIVITÄT",
    noActivity: "Noch keine Aktivität gemeldet.",
    dashboardError: "Dashboard-Fehler",
    autoUpdateFound: "Update gefunden – Installation startet",
    autoUpdateFailed: "Update-Prüfung fehlgeschlagen; aktuelle Version läuft weiter",
  },
  en: {
    language: "Language",
    online: "ONLINE",
    stopped: "STOPPED",
    player: "PLAYER",
    money: "Money",
    hacking: "Hacking",
    sourceFiles: "Source Files",
    resources: "RESOURCES",
    homeRam: "Home RAM",
    ramPurchase: "RAM buy",
    ramAutomatic: "automatic",
    ramManual: "manual only",
    ramWaiting: "automatic · waiting for money",
    ramUnavailable: "waiting for free module RAM",
    ramComplete: "goal reached",
    ramChecking: "checking",
    network: "Network",
    rootedServers: "servers with root access",
    automation: "AUTOMATION",
    mode: "Mode",
    bootstrap: "BOOTSTRAP (minimal)",
    lightweight: "STARTUP (lightweight)",
    medium: "MID STAGE (RAM + Source Files)",
    full: "FULL OPERATION",
    homeExpansion: "Home RAM goal",
    allModulesReleased: "All modules released at {ram}",
    modules: "Modules",
    active: "active",
    executable: "executable",
    phase: "phase",
    processes: "processes",
    threads: "threads",
    dashboard: "Dashboard",
    autoUpdate: "Auto-update",
    updateDisabled: "disabled",
    updateChecking: "checking",
    updateCurrent: "up to date",
    updateFound: "found · installation starting",
    updateFailed: "check failed",
    updateUnknown: "not checked yet",
    nextUpdateCheck: "next check",
    efficiency: "EFFICIENCY",
    moneyPerSecond: "Money avg/s",
    runTime: "Run time",
    augmentations: "Augs",
    workers: "Workers",
    manualActions: "MANUAL ACTIONS",
    noNotices: "No current notices",
    recentActivity: "RECENT ACTIVITY",
    noActivity: "No activity reported yet.",
    dashboardError: "Dashboard error",
    autoUpdateFound: "Update found — starting installation",
    autoUpdateFailed: "Update check failed; the current version keeps running",
  },
});

const ENGLISH_EXACT = new Map([
  ["Kein geeignetes Hacking-Ziel", "No suitable hacking target"],
  ["Worker-Datei fehlt", "Worker file is missing"],
  ["Kein freier RAM für Hacking-Worker", "No free RAM for hacking workers"],
  ["Home-Upgrades müssen noch manuell gekauft werden", "Home upgrades still need to be purchased manually"],
  ["Home-RAM muss noch manuell erweitert werden", "Home RAM still needs to be upgraded manually"],
  ["Home-RAM mit höchster Priorität erweitert", "Home RAM upgraded with highest priority"],
  ["Home-RAM ist automatisch kaufbar", "Home RAM can be purchased automatically"],
  ["Home-RAM ist nur manuell kaufbar", "Home RAM can only be purchased manually"],
  ["autoDoIt spart auf Home-RAM", "autoDoIt is saving for Home RAM"],
  ["Automatischer Home-RAM-Kauf ist noch gesperrt", "Automatic Home RAM purchasing is still locked"],
  ["Home-Kerne müssen noch manuell erweitert werden", "Home cores still need to be upgraded manually"],
  ["Home-Server erweitert", "Home server upgraded"],
  ["Home-Upgrade wartet auf Budget", "Home upgrade is waiting for budget"],
  ["TOR und Programme können noch nicht automatisiert werden", "TOR and programs cannot be automated yet"],
  ["TOR-Router gekauft", "TOR router purchased"],
  ["TOR-Router wartet auf ausreichend Geld", "TOR router is waiting for enough money"],
  ["Cloudserver gekauft", "Cloud servers purchased"],
  ["Cloudserver erweitert", "Cloud servers upgraded"],
  ["Cloudserver spart auf den Erstkauf", "Cloud server is saving for the first purchase"],
  ["Cloudserver warten auf Upgrade-Budget", "Cloud servers are waiting for upgrade budget"],
  ["Hacknet schneller erweitert", "Hacknet upgraded faster"],
  ["Hacknet wartet auf Budget", "Hacknet is waiting for budget"],
  ["Keine Coding Contracts gefunden", "No Coding Contracts found"],
  ["Coding Contracts automatisch gelöst", "Coding Contracts solved automatically"],
  ["Coding Contract konnte nicht gelesen werden", "Coding Contract could not be read"],
  ["Contract-Solver benötigt eine Korrektur", "Contract solver needs a correction"],
  ["Contract-Antwortformat wurde abgelehnt", "Contract answer format was rejected"],
  ["Coding-Contract-Lösung wurde abgelehnt", "Coding Contract solution was rejected"],
  ["Unbekannter Coding-Contract-Typ gefunden", "Unknown Coding Contract type found"],
  ["Weitere Server warten auf ein Port-Programm", "More servers are waiting for a port program"],
  ["Netzwerkübernahme wartet auf ein Port-Programm", "Network takeover is waiting for a port program"],
  ["Das Programm-Modul kauft es automatisch, sobald genügend Geld verfügbar ist.", "The program module will purchase it automatically once enough money is available."],
  ["autoDoIt übernimmt danach sofort alle damit erreichbaren Server.", "autoDoIt will immediately take over every server unlocked by it."],
  ["Hacking-Worker verteilt", "Hacking workers deployed"],
  ["Fraktionen benötigen noch manuelle Bedienung", "Factions still require manual interaction"],
  ["Fraktionsarbeit pausiert für Gang-Freischaltung", "Faction work paused to unlock a gang"],
  ["Augmentierungen können noch nicht automatisch verwaltet werden", "Augmentations cannot be automated yet"],
  ["Augmentierungen werden installiert", "Installing augmentations"],
  ["Augmentierungen werden gesammelt", "Collecting augmentations"],
  ["Augmentierungen warten auf das Home-RAM-Ziel", "Augmentations are waiting for the Home RAM goal"],
  ["Backdoors müssen noch manuell installiert werden", "Backdoors still need to be installed manually"],
  ["Jobs können noch nicht automatisiert werden", "Jobs cannot be automated yet"],
  ["Automatische Jobsteuerung verfügbar", "Automatic job control is available"],
  ["Jobentscheidung erkannt", "Job decision detected"],
  ["Job oder Beförderung erhalten", "Job or promotion obtained"],
  ["Noch kein passender Firmenjob verfügbar", "No suitable company job available yet"],
  ["BitNode-Abschluss ist noch nicht automatisierbar", "BitNode completion cannot be automated yet"],
  ["The Red Pill ist installiert", "The Red Pill is installed"],
  ["Gang-Automatisierung ist gesperrt", "Gang automation is locked"],
  ["Negatives Karma für die Gang wird aufgebaut", "Building negative karma for the gang"],
  ["Gang kann noch nicht gegründet werden", "Gang cannot be created yet"],
  ["Gang wird automatisch verwaltet", "Gang is being managed automatically"],
  ["IPvGO ist in diesem Spielstand noch nicht verfügbar", "IPvGO is not available in this save yet"],
  ["IPvGO spielt selbstständig", "IPvGO is playing automatically"],
  ["IPvGO konnte nicht fortgesetzt werden", "IPvGO could not continue"],
  ["Sleeve-Automatisierung ist gesperrt", "Sleeve automation is locked"],
  ["Sleeves werden automatisch verwaltet", "Sleeves are being managed automatically"],
  ["Bladeburner-Automatisierung ist gesperrt", "Bladeburner automation is locked"],
  ["Bladeburner-Division beigetreten", "Joined the Bladeburner division"],
  ["Training für Bladeburner gestartet", "Started training for Bladeburner"],
  ["Bladeburner-Aufnahmekriterien fehlen", "Bladeburner entry requirements are not met"],
  ["Bladeburner-Aktion gewählt", "Bladeburner action selected"],
  ["TIX-API gekauft", "TIX API purchased"],
  ["TIX-API ist noch nicht verfügbar", "TIX API is not available yet"],
  ["4S Market Data TIX API gekauft", "4S Market Data TIX API purchased"],
  ["Aktienhandel wartet auf 4S-Daten", "Stock trading is waiting for 4S data"],
  ["4S-Aktienhandel aktiv", "4S stock trading active"],
  ["Corporation-Automatisierung ist gesperrt", "Corporation automation is locked"],
  ["Corporation gegründet", "Corporation created"],
  ["Corporation kann noch nicht gegründet werden", "Corporation cannot be created yet"],
  ["Corporation wartet auf das Home-RAM-Ziel", "Corporation is waiting for the Home RAM goal"],
  ["Agriculture-Division gegründet", "Agriculture division created"],
  ["Corporation spart auf Agriculture", "Corporation is saving for Agriculture"],
  ["Corporation wird automatisch verwaltet", "Corporation is being managed automatically"],
  ["Casino wartet auf Source-File 4", "Casino is waiting for Source-File 4"],
  ["Casino-Startphase aktiv", "Casino startup phase active"],
  ["Casino-Verlust wird zurückgesetzt", "Resetting a casino loss"],
  ["Casino-Automatik braucht einmal Hilfe", "Casino automation needs one manual step"],
  ["Casino-Ziel erreicht", "Casino target reached"],
  ["Casino vollständig abgeschlossen", "Casino fully completed"],
  ["Darknet benötigt DarkscapeNavigator.exe", "Darknet requires DarkscapeNavigator.exe"],
  ["Darknet-Einstieg ist momentan instabil", "Darknet entry is currently unstable"],
  ["Darknet wartet auf automatisch freigegebenen RAM", "Darknet is waiting for automatically released RAM"],
  ["Darknet bereitet einen schnellen Arbeiter vor", "Darknet is preparing a fast worker"],
  ["Darknet-Arbeiter wird erneut gestartet", "Restarting the Darknet worker"],
  ["Darknet-Erkundung gestartet", "Darknet exploration started"],
  ["Beschleunigte Darknet-Erkundung gestartet", "Accelerated Darknet exploration started"],
  ["Darknet trainiert Charisma automatisch", "Darknet is training Charisma automatically"],
  ["Darknet-Servermigration wird geladen", "Charging Darknet server migration"],
  ["Darknet-Verbindung wird erneut aufgebaut", "Rebuilding the Darknet connection"],
  ["Darknet-Hilfsarbeiter wartet", "Darknet support worker is waiting"],
  ["Darknet-Einstiegsarbeiter wartet", "Darknet entry worker is waiting"],
  ["Der RAM- und Crawler-Starter wurde auf dem Nachbarserver gestartet.", "The RAM and crawler launcher was started on the neighboring server."],
  ["SF-1: Reality Alteration noch manuell", "SF-1: Reality Alteration still requires a manual step"],
  ["SF-1: True Recursion noch manuell", "SF-1: True Recursion still requires a manual step"],
  ["SF-1: Edit Save File noch manuell", "SF-1: Edit Save File still requires a manual step"],
  ["SF-1-Risikomodus benötigt die Desktop-Version", "SF-1 risk mode requires the desktop version"],
  ["SF-1-Risikomodus: Save wird geprüft und gesichert", "SF-1 risk mode: validating and backing up the save"],
  ["SF-1-Risikomodus sicher abgebrochen", "SF-1 risk mode stopped safely"],
  ["Source-File -1 vollständig: 11/11", "Source-File -1 complete: 11/11"],
  ["SF-1: Save-Einträge erledigt, automatische Prüfung läuft", "SF-1: save entries complete, automatic checks are running"],
  ["Darknet ist festgefahren – Webstorm wird vorbereitet", "Darknet is stuck — preparing Webstorm"],
  ["STORM_SEED ausgelöst – Darknet wird neu aufgebaut", "STORM_SEED triggered — rebuilding the Darknet"],
  ["STORM_SEED konnte nicht ausgelöst werden", "STORM_SEED could not be triggered"],
]);

const ENGLISH_LINES = new Map([
  ["autoDoIt prüft diese Voraussetzung später erneut.", "autoDoIt will check this requirement again later."],
  ["autoDoIt prüft den Stand später erneut.", "autoDoIt will check the status again later."],
  ["Nächste Schritte:", "Next steps:"],
  ["Noch kein erreichbarer Server besitzt Geld und Root-Zugriff.", "No reachable server with money and root access exists yet."],
  ["Einige Male n00dles manuell hacken oder das Root-Modul weiterlaufen lassen.", "Hack n00dles manually a few times or keep the rooting module running."],
  ["Die vollständige Repository-Struktur erneut nach Bitburner kopieren.", "Copy the complete repository structure into Bitburner again."],
  ["Home-RAM erweitern oder einen Server mit freiem RAM übernehmen.", "Upgrade Home RAM or root a server with free RAM."],
  ["Automatische RAM- und Kern-Upgrades benötigen Source-File 4 oder BitNode 4.", "Automatic RAM and core upgrades require Source-File 4 or BitNode 4."],
  ["Der automatische RAM-Kauf benötigt Source-File 4 oder BitNode 4.", "Automatic RAM purchasing requires Source-File 4 or BitNode 4."],
  ["Automatische Kern-Upgrades benötigen Source-File 4 oder BitNode 4.", "Automatic core upgrades require Source-File 4 or BitNode 4."],
  ["Home-RAM bei verfügbarem Budget manuell erweitern.", "Upgrade Home RAM manually when the budget is available."],
  ["Home-Kerne bei verfügbarem Budget manuell erweitern.", "Upgrade Home cores manually when the budget is available."],
  ["Optionale Käufe sind bis zum RAM-Ziel pausiert.", "Optional purchases are paused until the RAM goal is reached."],
  ["Hacknet und Cloudserver erhalten je 1 % Wachstumsbudget; übrige optionale Käufe bleiben pausiert.", "Hacknet and cloud servers each receive a 1% growth budget; other optional purchases remain paused."],
  ["Priorität: Home-RAM bis zur 50%-Stufe.", "Priority: Home RAM until the 50% stage."],
  ["Priorität: Home-RAM und BitNode-Abschluss gleichauf.", "Priority: Home RAM and BitNode completion are equal."],
  ["Home-RAM und BitNode-Abschluss haben dieselbe Priorität.", "Home RAM and BitNode completion have the same priority."],
  ["Der automatische Kauf benötigt BitNode 4 oder Source-File 4.", "Automatic purchasing requires BitNode 4 or Source-File 4."],
  ["Käufe und Installations-Resets sind vorübergehend pausiert.", "Purchases and installation resets are temporarily paused."],
  ["Die selbstfinanzierte Gründung würde das RAM-Budget verbrauchen.", "Self-funded creation would consume the RAM budget."],
  ["Das Ziel für gleichzeitigen Modulbetrieb ist bereits erreicht.", "The simultaneous module operation goal has already been reached."],
  ["Das reine RAM-Kaufmodul benötigt auf niedriger Source-File-4-Stufe selbst freien Home-RAM.", "At a low Source-File 4 level, the RAM-only purchasing module itself requires free Home RAM."],
  ["Falls das Modul nicht startet, Home-RAM zunächst manuell auf mindestens 64 GiB erweitern.", "If the module does not start, first upgrade Home RAM manually to at least 64 GiB."],
  ["Die Singularity-API benötigt BitNode 4 oder Source-File 4.", "The Singularity API requires BitNode 4 or Source-File 4."],
  ["Hacking-Worker verwenden sie automatisch.", "Hacking workers use them automatically."],
  ["Bestehende Server werden sicher erweitert statt gelöscht.", "Existing servers are safely upgraded instead of deleted."],
  ["Bei vollem Limit wird immer der schwächste Server erweitert.", "When the limit is full, the weakest server is always upgraded."],
  ["Contract vorläufig manuell lösen oder auf ein autoDoIt-Update warten.", "Solve the contract manually for now or wait for an autoDoIt update."],
  ["Kein weiterer automatischer Versuch wird in diesem Durchlauf ausgeführt.", "No further automatic attempt will be made during this pass."],
  ["Den unbekannten Typ für das nächste autoDoIt-Update melden.", "Report the unknown type for the next autoDoIt update."],
  ["Bis dahin keine Versuche für diesen Contract verbrauchen.", "Do not consume any attempts for this contract until then."],
  ["Einladungen, Fraktionsarbeit und Anforderungen benötigen Source-File 4 oder BitNode 4.", "Invitations, faction work, and requirements need Source-File 4 or BitNode 4."],
  ["Kauf und Installation benötigen Source-File 4 oder BitNode 4.", "Purchasing and installation require Source-File 4 or BitNode 4."],
  ["Augmentierungen vorläufig manuell kaufen und installieren.", "Purchase and install augmentations manually for now."],
  ["autoDoIt startet nach dem Reset automatisch erneut.", "autoDoIt restarts automatically after the reset."],
  ["Bewerbungen und Firmenarbeit benötigen Source-File 4 oder BitNode 4.", "Applications and company work require Source-File 4 or BitNode 4."],
  ["Das Jobmodul übernimmt Bewerbungen, Beförderungen und Firmenarbeit, sobald es in den freien RAM passt.", "The job module handles applications, promotions, and company work as soon as it fits into free RAM."],
  ["autoDoIt versucht es nach weiteren Skill-Steigerungen erneut.", "autoDoIt will try again after further skill increases."],
  ["Die Gang-API benötigt BitNode 2 oder Source-File 2.", "The Gang API requires BitNode 2 or Source-File 2."],
  ["Die Sleeve-API benötigt BitNode 10 oder Source-File 10.", "The Sleeve API requires BitNode 10 or Source-File 10."],
  ["Die Corporation-API benötigt BitNode 3 oder Source-File 3.", "The Corporation API requires BitNode 3 or Source-File 3."],
  ["Für automatische Aktiengeschäfte wird TIX-API-Zugriff benötigt.", "Automated stock trading requires TIX API access."],
  ["Ohne verlässliche Prognose führt autoDoIt keine spekulativen Käufe aus.", "autoDoIt does not make speculative purchases without a reliable forecast."],
  ["Die sichere automatische Save-Sicherung und der offizielle Importweg sind in dieser Umgebung nicht verfügbar.", "Safe automatic save backup and the official import route are unavailable in this environment."],
  ["Es wurde kein unbekannt aufgebautes Save importiert.", "No save with an unknown structure was imported."],
  ["Die API benötigt BitNode 6/7 oder Source-File 6/7.", "The API requires BitNode 6/7 or Source-File 6/7."],
  ["Ein entsprechendes BitNode abschließen.", "Complete the corresponding BitNode."],
  ["Für den Beitritt werden ausreichend hohe Kampfwerte benötigt.", "High enough combat stats are required to join."],
  ["Stärke, Verteidigung, Geschicklichkeit und Agilität trainieren.", "Train strength, defense, dexterity, and agility."],
  ["BitNode 3 abschließen, um Source-File 3 zu erhalten.", "Complete BitNode 3 to obtain Source-File 3."],
  ["Außerhalb von BitNode 3 wird ausreichend eigenes Startkapital benötigt.", "Outside BitNode 3, sufficient self-funded starting capital is required."],
  ["Die Startbedingungen dieses BitNodes sind noch nicht erfüllt.", "This BitNode's starting conditions are not met yet."],
  ["autoDoIt startet das IPvGO-Modul automatisch, sobald die API freigeschaltet ist.", "autoDoIt starts the IPvGO module automatically once the API is unlocked."],
  ["IPvGO einmal im linken Menü öffnen; autoDoIt versucht es danach erneut.", "Open IPvGO once from the left menu; autoDoIt will retry afterwards."],
  ["BitNode 2 abschließen, um Source-File 2 zu erhalten.", "Complete BitNode 2 to obtain Source-File 2."],
  ["Aktion: Homicide", "Action: Homicide"],
  ["Es wird außerdem die Mitgliedschaft in einer geeigneten Gang-Fraktion benötigt.", "Membership in a suitable gang faction is also required."],
  ["Verbrechen ausführen, bis genügend negatives Karma erreicht ist.", "Commit crimes until enough negative karma has been reached."],
  ["Einer geeigneten Fraktion wie Slum Snakes oder NiteSec beitreten.", "Join a suitable faction such as Slum Snakes or NiteSec."],
  ["Weiter Geld verdienen; autoDoIt versucht den Kauf später erneut.", "Keep earning money; autoDoIt will retry the purchase later."],
  ["Das Programm-Modul kauft oder erstellt es automatisch, sobald Singularity verfügbar ist.", "The programs module purchases or creates it automatically once Singularity is available."],
  ["Weiterleitung zu Stats; alle übrigen Module werden jetzt gestartet.", "Opening Stats; all remaining modules are starting now."],
  ["Für automatisches Reisen und Öffnen des Casinos wird die Singularity-API benötigt.", "Automatic travel and opening the casino require the Singularity API."],
  ["Bis dahin kann Blackjack manuell gespielt werden.", "Until then, Blackjack can be played manually."],
  ["Blackjack wird exklusiv gespielt; bei einem Verlust wird der letzte Speicherstand geladen.", "Blackjack is played exclusively; after a loss, the latest save is reloaded."],
  ["Overview aufklappen und das Spiel im Vordergrund lassen.", "Expand Overview and keep the game in the foreground."],
  ["autoDoIt versucht die Casino-Startphase danach erneut.", "autoDoIt will retry the casino startup phase afterwards."],
  ["Das Iker Molina Casino konnte nicht geöffnet werden.", "The Iker Molina Casino could not be opened."],
  ["Die Casino-Oberfläche wurde nicht gerendert.", "The casino interface was not rendered."],
  ["Der Overview-Speicherknopf ist nicht sichtbar. Overview einmal aufklappen.", "The Overview save button is not visible. Expand Overview once."],
  ["Benötigtes Bedienelement wurde nicht gefunden.", "A required control could not be found."],
  ["RAM ist innerhalb des aktuellen Budgets bereits optimal.", "RAM is already optimal within the current budget."],
  ["Keine zusätzlichen Kerne gekauft.", "No additional cores purchased."],
  ["Vorläufig manuell den bestmöglichen Software-Job annehmen; falls nicht verfügbar, IT wählen.", "For now, manually take the best Software job available; choose IT if none is available."],
  ["TOR und benötigte Programme vorerst manuell im Terminal/Dark Web kaufen.", "Purchase TOR and required programs manually from the terminal/Dark Web for now."],
  ["BitNode 4 abschließen, um Source-File 4 freizuschalten.", "Complete BitNode 4 to unlock Source-File 4."],
  ["Bei CSEC, avmnite-02h, I.I.I.I und run4theh111z manuell Backdoors installieren.", "Install backdoors on CSEC, avmnite-02h, I.I.I.I, and run4theh111z manually."],
  ["Fraktionseinladungen manuell prüfen und sinnvolle Fraktionen beitreten.", "Check faction invitations manually and join useful factions."],
  ["Für benötigte Augmentierungen manuell Fraktionsreputation sammeln.", "Earn faction reputation manually for required augmentations."],
  ["Das Gang-Modul baut zuerst das benötigte negative Karma auf.", "The gang module is building the required negative karma first."],
  ["Der Wechsel zum nächsten BitNode benötigt Source-File 4 oder BitNode 4.", "Switching to the next BitNode requires Source-File 4 or BitNode 4."],
  ["The Red Pill installieren.", "Install The Red Pill."],
  ["w0r1d_d43m0n finden, Root-Zugriff erhalten und manuell abschließen.", "Find w0r1d_d43m0n, gain root access, and complete it manually."],
  ["Als frühes Ziel BitNode 4 wählen.", "Choose BitNode 4 as an early target."],
  ["w0r1d_d43m0n ist noch nicht entdeckt oder besitzt noch keinen Root-Zugriff.", "w0r1d_d43m0n has not been discovered yet or does not have root access yet."],
  ["Fortschritt ist ausreichend; autoDoIt wird nach dem Wechsel neu gestartet.", "Progress is sufficient; autoDoIt will restart after the switch."],
  ["Im Script-Debugger ns.alterReality() anhalten und die lokale Variable x vor der Abschlussprüfung auf true setzen.", "Pause ns.alterReality() in the script debugger and set the local variable x to true before the final check."],
  ["Nach New Tokyo reisen, Arcade öffnen und das eingebettete Bitburner-Classic-Minispiel abschließen.", "Travel to New Tokyo, open the Arcade, and complete the embedded Bitburner Classic minigame."],
  ["Save exportieren/sichern und \"EditSaveFile\" im dekodierten Player-exploits-Array ergänzen; danach wieder importieren.", "Export and back up the save, add \"EditSaveFile\" to the decoded Player exploits array, then import it again."],
  ["Der offizielle Import wird jetzt bestätigt; Bitburner lädt danach neu.", "The official import is being confirmed; Bitburner will reload afterwards."],
  ["Die automatischen Exploit-Prüfungen laufen; der Prototype-Test kann bis zu 15 Minuten dauern.", "Automatic exploit checks are running; the prototype test can take up to 15 minutes."],
  ["autoDoIt wartet auf genügend freien Home-RAM für die zeitabhängigen Prüfungen.", "autoDoIt is waiting for enough free Home RAM for the time-based checks."],
  ["Die verbleibende Stufe stammt aus einem normalen Exploit-Test und wird weiter automatisch versucht.", "The remaining level comes from a normal exploit test and will keep being attempted automatically."],
  ["Alle verfügbaren fraktionsspezifischen Augmentierungen sind bereits abgeschlossen.", "All available faction-specific augmentations are already complete."],
  ["Ohne Source-File 4 kann autoDoIt das Programm noch nicht selbst kaufen.", "Without Source-File 4, autoDoIt cannot purchase the program automatically yet."],
  ["Source-File 4 fehlt; autoDoIt kann Bewerbung und Firmenarbeit noch nicht selbst starten.", "Source-File 4 is missing; autoDoIt cannot start the application or company work itself yet."],
  ["TOR kaufen und im Terminal „buy DarkscapeNavigator.exe“ ausführen.", "Purchase TOR and run “buy DarkscapeNavigator.exe” in the terminal."],
  ["Der Einstiegsserver hat sich während des Starts verändert.", "The entry server changed during startup."],
  ["Caches, Passworthinweise und erreichbare Server werden automatisch bearbeitet.", "Caches, password hints, and reachable servers are handled automatically."],
  ["Belohnung eingesammelt.", "Reward collected."],
  ["autoDoIt prüft Logs und Server später erneut.", "autoDoIt will check logs and servers again later."],
  ["Priorität: Schockabbau → Synchronisierung → Homicide.", "Priority: shock recovery → synchronization → Homicide."],
  ["Automatisches Verbinden und installBackdoor benötigen Source-File 4 oder BitNode 4.", "Automatic connection and installBackdoor require Source-File 4 or BitNode 4."],
  ["Hinweis: kein statischer Hinweis", "Hint: no static hint"],
  ["Der offizielle Importdialog wurde nicht geöffnet.", "The official import dialog was not opened."],
  ["Die zweite Importbestätigung wurde nicht gefunden.", "The second import confirmation was not found."],
  ["Der bestätigte Import hat Bitburner nicht innerhalb von 30 Sekunden neu geladen.", "The confirmed import did not reload Bitburner within 30 seconds."],
]);

export function normalizeLanguage(value) {
  return String(value).trim().toLowerCase() === LANGUAGE.en ? LANGUAGE.en : LANGUAGE.de;
}

export function readLanguage(ns) {
  return normalizeLanguage(ns.read(LANGUAGE_FILE));
}

export function writeLanguage(ns, language) {
  const normalized = normalizeLanguage(language);
  ns.write(LANGUAGE_FILE, normalized, "w");
  return normalized;
}

export function dashboardText(language, key, values = {}) {
  const normalized = normalizeLanguage(language);
  let text = DASHBOARD_TEXT[normalized]?.[key] ?? DASHBOARD_TEXT.de[key] ?? key;
  for (const [name, value] of Object.entries(values)) {
    text = text.replaceAll(`{${name}}`, String(value));
  }
  return text;
}

function translateDynamic(text) {
  const patterns = [
    [/^MANUELLE AKTION:\s*(.+)$/i, (_match, value) => `ACTION REQUIRED: ${translateEnglish(value)}`],
    [/^Netzwerkübernahme wartet auf (.+)$/, "Network takeover is waiting for $1"],
    [/^(\d+\.\s*)(.+)$/, (_match, prefix, value) => `${prefix}${translateEnglish(value)}`],
    [/^(\d+) neue Server übernommen$/, "$1 new servers rooted"],
    [/^(\d+) Netzwerkziele wurden geprüft\.$/, "$1 network targets checked."],
    [/^(\d+) Server besitzen die aktuelle Worker-Version\.$/, "$1 servers have the current worker version."],
    [/^(\d+) Threads gestartet\.$/, "$1 threads started."],
    [/^(\d+) Symbole geprüft\.$/, "$1 symbols checked."],
    [/^(\d+) Sleeves geprüft\.$/, "$1 sleeves checked."],
    [/^(\d+) eigene Züge seit Modulstart\.$/, "$1 moves made since the module started."],
    [/^(\d+) neue Augmentierungen\.$/, "$1 new augmentations."],
    [/^(\d+) Käufe für (.+)\.$/, "$1 purchases for $2."],
    [/^(\d+) Kern-Upgrades gekauft\.$/, "$1 core upgrades purchased."],
    [/^(\d+) Bladeburner-Skill-Upgrades gekauft;\s*(.+) Punkte übrig\.$/, "$1 Bladeburner skill upgrades purchased; $2 points remaining."],
    [/^(\d+) neue Server mit zusammen (.+) RAM\.$/, "$1 new servers with $2 RAM in total."],
    [/^(\d+) Upgrades, zusätzlich (.+) RAM\.$/, "$1 upgrades, adding $2 RAM."],
    [/^(\d+)\/(\d+) für den nächsten Installations-Reset\.$/, "$1/$2 for the next installation reset."],
    [/^(\d+) Mitglieder, (.+) Respekt\.$/, "$1 members, $2 respect."],
    [/^(\d+)\/(\d+) Städte$/, "$1/$2 cities"],
    [/^Geld:\s*(.+)$/, "Money: $1"],
    [/^Sicherheit:\s*(.+)$/, "Security: $1"],
    [/^Aktuelles Hacking-Level:\s*(.+)$/, "Current hacking level: $1"],
    [/^Als Nächstes fehlt wahrscheinlich (.+)\.$/, "The next likely missing program is $1."],
    [/^(\d+) Server sind noch durch Port-Anforderungen gesperrt\.$/, "$1 servers are still locked by port requirements."],
    [/^Port-Programme:\s*(\d+)\/(\d+);\s*nächste Root-Stufe benötigt (\d+) offene Ports\.$/, "Port programs: $1/$2; the next root tier requires $3 open ports."],
    [/^Als Nächstes fehlt (.+)\.$/, "The next missing program is $1."],
    [/^(\d+) weitere Server werden damit direkt übernehmbar\.$/, "$1 more servers will become immediately accessible."],
    [/^Im Menü „Create Program“ (.+) erstellen\.$/, "Create $1 in the “Create Program” menu."],
    [/^Hacking auf (.+) steigern oder TOR und (.+) manuell kaufen\.$/, "Raise Hacking to $1 or manually purchase TOR and $2."],
    [/^Aktuell:\s*(.+)$/, "Current: $1"],
    [/^Karma:\s*(.+)\s+\(benötigt normalerweise (.+)\)\.$/, "Karma: $1 (normally requires $2)."],
    [/^Territorialkrieg:\s*aktiv$/, "Territory warfare: active"],
    [/^Territorialkrieg:\s*inaktiv$/, "Territory warfare: inactive"],
    [/^(.+) Gewinn seit der letzten Installation\.$/, "$1 profit since the last installation."],
    [/^(.+) RAM-Upgrades:\s*(.+)$/, "$1 RAM upgrades: $2"],
    [/^(\d+) Upgrades:\s*(.+)$/, "$1 upgrades: $2"],
    [/^RAM-Ziel für gleichzeitigen Modulbetrieb:\s*(.+)\.$/, "RAM goal for simultaneous module operation: $1."],
    [/^Home-RAM manuell bis (.+) erweitern\.$/, "Upgrade Home RAM manually to $1."],
    [/^Home-RAM zunächst manuell auf mindestens (.+) erweitern\.$/, "First upgrade Home RAM manually to at least $1."],
    [/^Ziel für alle Module gleichzeitig:\s*(.+)\.$/, "Goal for all modules simultaneously: $1."],
    [/^Aktuell:\s*(.+) \/ Ziel:\s*(.+)$/, "Current: $1 / Goal: $2"],
    [/^Home-RAM:\s*(.+) \/ (.+)$/, "Home RAM: $1 / $2"],
    [/^Nächstes RAM-Upgrade:\s*(.+)$/, "Next RAM upgrade: $1"],
    [/^Nächstes Kern-Upgrade:\s*(.+)$/, "Next core upgrade: $1"],
    [/^Freigegebenes Budget:\s*(.+)$/, "Allocated budget: $1"],
    [/^Nächstes Upgrade:\s*(.+)$/, "Next upgrade: $1"],
    [/^Freigegeben:\s*(.+)$/, "Allocated: $1"],
    [/^Angespartes Hacknet-Budget:\s*(.+)\.$/, "Saved Hacknet budget: $1."],
    [/^Angespartes Cloud-Budget:\s*(.+)\.$/, "Saved cloud budget: $1."],
    [/^Kleinster geplanter Server:\s*(.+) für (.+)\.$/, "Smallest planned server: $1 for $2."],
    [/^(\d+) von (\d+) gefundenen Contracts gelöst\.$/, "$1 of $2 discovered contracts solved."],
    [/^(\d+) Contract\(s\) wurden sicher übersprungen\.$/, "$1 contract(s) were safely skipped."],
    [/^Typ:\s*(.+)$/, "Type: $1"],
    [/^Vorherige Versuche verfügbar:\s*(.+)\.$/, "Attempts previously available: $1."],
    [/^Bis zu (.+) sind pro Durchlauf freigegeben\.$/, "Up to $1 is allocated per cycle."],
    [/^(.+) benötigt (.+) pro Thread\.$/, "$1 requires $2 per thread."],
    [/^Spare für (.+)$/, "Saving for $1"],
    [/^Preis:\s*(.+)$/, "Price: $1"],
    [/^(.+) gekauft$/, "$1 purchased"],
    [/^Fraktion beigetreten:\s*(.+)$/, "Joined faction: $1"],
    [/^Augmentierung gekauft:\s*(.+)$/, "Augmentation purchased: $1"],
    [/^Fraktion:\s*(.+)$/, "Faction: $1"],
    [/^Fraktionsarbeit gestartet:\s*(.+)$/, "Faction work started: $1"],
    [/^(.+) bietet keine Arbeit an$/, "$1 offers no work"],
    [/^Ziel:\s*(\d+) Threads für Passwort-, RAM- und Migrationsbeschleunigung\.$/, "Target: $1 threads for faster passwords, RAM release, and migrations."],
    [/^Ziel:\s*(.+)$/, "Target: $1"],
    [/^Arbeitsart:\s*(.+)$/, "Work type: $1"],
    [/^Benötigt für (.+):\s*(.+) Reputation\.$/, "Required for $1: $2 reputation."],
    [/^Verbindung zu (.+) fehlgeschlagen$/, "Connection to $1 failed"],
    [/^Backdoor installiert:\s*(.+)$/, "Backdoor installed: $1"],
    [/^Firmenarbeit bei (.+) gestartet$/, "Company work started at $1"],
    [/^Bester manueller Job:\s*(.+)$/, "Best manual job: $1"],
    [/^Empfehlung:\s*(.+)$/, "Recommendation: $1"],
    [/^Stadt:\s*(.+)$/, "City: $1"],
    [/^Geschätzter Grundverdienst:\s*(.+) pro Sekunde\.$/, "Estimated base earnings: $1 per second."],
    [/^Nach (.+) reisen\.$/, "Travel to $1."],
    [/^Bei (.+) als (.+) bewerben\.$/, "Apply to $1 as $2."],
    [/^Bei (.+) die Firmenarbeit als (.+) starten\.$/, "Start company work at $1 as $2."],
    [/^Berufspriorität:\s*(.+), danach (.+)\.$/, "Job priority: $1, followed by $2."],
    [/^autoDoIt hat (.+) als bevorzugtes Berufsfeld festgelegt;\s*(.+) ist die Ausweichwahl\.$/, "autoDoIt selected $1 as the preferred career field; $2 is the fallback."],
    [/^Vorläufig manuell den bestmöglichen (.+)-Job annehmen;\s*falls nicht verfügbar, (.+) wählen\.$/, "For now, manually take the best $1 job available; choose $2 if none is available."],
    [/^autoDoIt bevorzugt (.+), danach (.+)\.$/, "autoDoIt prefers $1, followed by $2."],
    [/^Wechsel zu BitNode (.+)$/, "Switching to BitNode $1"],
    [/^Gang gegründet:\s*(.+)$/, "Gang created: $1"],
    [/^IPvGO-Partie gegen (.+) gestartet$/, "IPvGO game against $1 started"],
    [/^Brettgröße:\s*(.+)$/, "Board size: $1"],
    [/^Aktueller Gegner:\s*(.+)$/, "Current opponent: $1"],
    [/^Corporation spart auf (.+)$/, "Corporation is saving for $1"],
    [/^Benötigt:\s*(.+)$/, "Required: $1"],
    [/^Kapital:\s*(.+)$/, "Funds: $1"],
    [/^Sicherung erstellt:\s*(.+)$/, "Backup created: $1"],
    [/^Ergänzt werden ausschließlich:\s*(.+)$/, "Only the following entries are added: $1"],
    [/^Source-File -1:\s*(.+)$/, "Source-File -1: $1"],
    [/^Darknet-RAM freigegeben:\s*(.+)$/, "Darknet RAM released: $1"],
    [/^Darknet-RAM wird automatisch freigegeben$/, "Darknet RAM is being released automatically"],
    [/^(.+):\s*(.+) frei, (.+) benötigt\.$/, "$1: $2 free, $3 required."],
    [/^RAM-Freigabe läuft mit (\d+) Threads\.$/, "RAM release is running with $1 threads."],
    [/^(.+) sind jetzt verfügbar\.$/, "$1 is now available."],
    [/^(.+):\s*(.+) frei\.$/, "$1: $2 free."],
    [/^Worker benötigt (.+);\s*autoDoIt versucht es erneut\.$/, "Worker requires $1; autoDoIt will retry."],
    [/^Darknet-Cache geöffnet:\s*(.+)$/, "Darknet cache opened: $1"],
    [/^Darknet-Zugang benötigt Hilfe:\s*(.+)$/, "Darknet access needs help: $1"],
    [/^Darknet löst (.+) erneut$/, "Darknet is retrying $1"],
    [/^Darknet-Server geöffnet:\s*(.+)$/, "Darknet server opened: $1"],
    [/^Darknet-Einstieg geöffnet:\s*(.+)$/, "Darknet entry opened: $1"],
    [/^Darknet-Crawler startet auf (.+)$/, "Darknet crawler is starting on $1"],
    [/^Leichter Darknet-Seeder startet auf (.+)$/, "Lightweight Darknet seeder is starting on $1"],
    [/^Darknet-Arbeiter passt nicht auf (.+)$/, "Darknet worker does not fit on $1"],
    [/^Darknet-Arbeiter auf (.+) beendet$/, "Darknet worker on $1 stopped"],
    [/^Darknet-Arbeiter auf (.+) wartet$/, "Darknet worker on $1 is waiting"],
    [/^Server:\s*(.+), Tiefe (.+)$/, "Server: $1, depth $2"],
    [/^Hinweis:\s*(.+)$/, "Hint: $1"],
    [/^Tiefe (.+), Modell (.+)$/, "Depth $1, model $2"],
    [/^(\d+) Threads bearbeiten Passwörter, Labyrinthe, RAM und Luftlücken\.$/, "$1 threads are handling passwords, labyrinths, RAM, and air gaps."],
    [/^Passworthinweise, Daten und aktive Rückmeldungen werden weiter ausgewertet\.$/, "Password hints, data, and interactive feedback will keep being evaluated."],
    [/^(.+) trägt seinen aktiven Arbeiter über mögliche Luftlücken\.$/, "$1 carries its active worker across possible air gaps."],
    [/^STORM_SEED auf Tiefe (.+);\s*erneute Prüfung in (.+) Minuten\.$/, "STORM_SEED at depth $1; checking again in $2 minutes."],
  ];
  for (const [pattern, replacement] of patterns) {
    if (pattern.test(text)) return text.replace(pattern, replacement);
  }
  return text;
}

export function translateEnglish(value) {
  const text = String(value);
  return ENGLISH_EXACT.get(text) ?? ENGLISH_LINES.get(text) ?? translateDynamic(text);
}

export function localizeEvent(event, language) {
  if (normalizeLanguage(language) !== LANGUAGE.en) return event;
  return {
    ...event,
    title: translateEnglish(event.title),
    lines: Array.isArray(event.lines) ? event.lines.map(translateEnglish) : [],
  };
}
